### PR TITLE
fix: Handle undefined JSONata timeout values gracefully

### LINKED ISSUE #1890: Handle Undefined .toString in Wait Until Node
### Describe the bug

Update `WaitUntilController.ts` to safely handle cases where JSONata expressions return `undefined`, preventing errors when `.toString()` is called on a non-existent value.

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/e311047a9dbd4995d4b674ebcd08cf3dda079b84/src/nodes/wait-until/WaitUntilController.ts#L208

### To Reproduce

_No response_

### Expected behavior

_No response_

### Screenshots

_No response_

### Example Flow

```json

```

### Environment Information

v0.78.2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ElshadHu**
Hi! I've reproduced this bug and have implemented a fix.

Closes #1890 

## The Problem
When a JSONata expression in the timeout field returns `undefined`

## My Solution
I've added a private helper method `#validateAndConvertTimeout()` that:
- Validates the JSONata result before calling `.toString()`
- Checks for `undefined`, `null`, `NaN`
- Throws a clear `InputError` instead of crashing
- Provides a helpful error message to users

If there is any issue, Please let me know.

### CODE REVIEW

File: src/nodes/wait-until/WaitUntilController.ts [hunk 1]
```diff
@@ -79,6 +79,24 @@ export default class WaitUntil extends InputOutputController<
         );
     }
 
+    #validateAndConvertTimeout(result: unknown): number {
+        const timeout = Number(result);
+
+        if (
+            result === undefined ||
```
Comment (zachowj) [inline src/nodes/wait-until/WaitUntilController.ts]: The `undefined` check can be removed `Number(undefined)` already evaluates to `NaN`.

File: src/nodes/wait-until/WaitUntilController.ts [hunk 2]
```diff
@@ -79,6 +79,19 @@ export default class WaitUntil extends InputOutputController<
         );
     }
 
+    #validateAndConvertTimeout(result: unknown): number {
+        const timeout = Number(result);
+
+        if (result === null || isNaN(timeout) || timeout < 0) {
+            throw new InputError(
+                ['ha-wait-until.error.invalid_timeout', { timeout }],
```
Comment (zachowj) [inline src/nodes/wait-until/WaitUntilController.ts]: A small UX issue here: if `result` is `null`, `Number(result)` evaluates to `0`. The validation correctly rejects it, but the error message reports `"Invalid value for timeout: 0"`, which is confusing for users because `0` is not the value they provided and is otherwise valid. Suggest using `String(result)` (or passing the raw `result`) in the error so the message reflects the original input.
